// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdminUploadBookTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void uT28ValidInput() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/admin_login.php/LMS_Group8/LMS%20code/admin_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) a")).click();
        driver.findElement(By.name("title")).click();
        driver.findElement(By.name("title")).sendKeys("105 Book");
        driver.findElement(By.name("keywords")).click();
        driver.findElement(By.name("keywords")).sendKeys("software testing");
        driver.findElement(By.name("file")).click();
        driver.findElement(By.name("image")).click();
        driver.findElement(By.cssSelector("button")).click();
    }
    @Test
    public void uT29emptybooktitle() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/admin_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) a")).click();
        driver.findElement(By.name("keywords")).click();
        driver.findElement(By.name("keywords")).sendKeys("software testing");
        driver.findElement(By.name("file")).click();
        driver.findElement(By.name("image")).click();
        driver.findElement(By.name("file")).click();
        driver.findElement(By.cssSelector("button")).click();
    }
    @Test
    public void uT30emptykeyword() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/admin_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) a")).click();
        driver.findElement(By.name("title")).click();
        driver.findElement(By.name("title")).sendKeys("102 bookkk");
        driver.findElement(By.name("keywords")).click();
        driver.findElement(By.name("file")).click();
        driver.findElement(By.name("image")).click();
        driver.findElement(By.cssSelector("button")).click();
    }
    @Test
    public void uT31emptypdffile() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/admin_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.cssSelector("label:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) a")).click();
        driver.findElement(By.name("title")).click();
        driver.findElement(By.name("title")).sendKeys("102 Boook");
        driver.findElement(By.name("keywords")).click();
        driver.findElement(By.name("keywords")).sendKeys("software testing");
        driver.findElement(By.name("image")).click();
        driver.findElement(By.cssSelector("button")).click();
    }
    @Test
    public void uT32emptyphoto() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/admin_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) a")).click();
        driver.findElement(By.name("title")).click();
        driver.findElement(By.name("title")).sendKeys("book");
        driver.findElement(By.name("keywords")).click();
        driver.findElement(By.name("keywords")).sendKeys("software testing");
        driver.findElement(By.name("file")).click();
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
    }
}
