// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UserViewallbookuserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void uT12Userviewallbookpage() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("hiruniwijerathna7@gmail.com");
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("000");
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) a")).click();
        driver.findElement(By.cssSelector(".book-container")).click();
        assertThat(driver.findElement(By.cssSelector(".book-card:nth-child(1) > h2")).getText(), is("Have you truly been born again of water and the Spirit"));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("View")).click();
        vars.put("win1265", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win1265").toString());
        driver.switchTo().window(vars.get("root").toString());
        driver.findElement(By.cssSelector(".book-card:nth-child(1) button")).click();
    }
}
