// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class UserLoginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void uT06ValidInput() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("hiruniwijerathna7@gmail.com");
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("000");
        driver.findElement(By.name("remember")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
    }
    @Test
    public void uT07invalidemail() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("hiruniwijerathna7@gmail.com");
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("hiruniwijerata7@gmail.com");
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("000");
        driver.findElement(By.name("remember")).click();
        driver.findElement(By.cssSelector(".login-button")).click();
    }
    @Test
    public void uT08Invalidpassword() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("hiruniwijerathna7@gmail.com");
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("159");
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.close();
    }
    @Test
    public void uT09emptyemail() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.cssSelector("label:nth-child(2)")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("123");
        driver.findElement(By.cssSelector(".login-button")).click();
    }
    @Test
    public void uT10emptypassword() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("hiruniwijerathna7@gmail.com");
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.close();
    }
    @Test
    public void uT11bothempty() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_login.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.cssSelector(".login-button")).click();
        driver.close();
    }
}
