// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class UserRegisterTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void uT01validinput() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_register.php/LMS_Group8/LMS%20code/user_register.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        {
            WebElement element = driver.findElement(By.name("name"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.name("name"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.name("name"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("Tharuka");
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("test@gmail.com");
        driver.findElement(By.id("re_password")).click();
        driver.findElement(By.id("re_password")).sendKeys("000");
        driver.findElement(By.name("terms and conditions")).click();
        driver.findElement(By.cssSelector(".register-button")).click();
    }
    @Test
    public void uT02existingemail() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_register.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("Thathsarani");
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("test@gmail.com");
        driver.findElement(By.id("re_password")).click();
        driver.findElement(By.id("re_password")).sendKeys("000");
        driver.findElement(By.name("terms and conditions")).click();
        driver.findElement(By.cssSelector(".register-button")).click();
    }
    @Test
    public void uT03invalidemailformat() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_register.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("Darshani");
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("test@ghvghvh.ugj");
        driver.findElement(By.id("re_password")).click();
        driver.findElement(By.id("re_password")).sendKeys("000");
        driver.findElement(By.cssSelector(".terms-conditions > label")).click();
        driver.findElement(By.cssSelector(".register-button")).click();
    }
    @Test
    public void uT04empty() {
        driver.get("http://localhost/LMS_Group8/LMS%20code/user_register.php");
        driver.manage().window().setSize(new Dimension(752, 816));
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("Insari");
        driver.findElement(By.name("terms and conditions")).click();
        driver.findElement(By.cssSelector(".register-button")).click();
    }
}
